- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
  vars:
    user_home: "{{ home }}"
    user_uid: "{{ uid }}"
    user_gid: "{{ gid }}"

  tasks:
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/packages.yml
    - include: tasts/gnome.yml
