- name: Install python-psutil package
  apt: name=python-psutil

- name: Install arc theme
  apt: name=arc-theme
  
- name: Set GTK theme
  become: true
  become_user: "{{ user_uid }}"
  dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Arc-Dark'"
    state: present
  
- name: Copy wallpaper file
  copy: src=files/wallpaper.jpg dest=/usr/share/backgrounds/wallpaper.jpg owner={{ user_uid }} group={{ user_gid }} mode=644

- name: Set GNOME wallpaper
  become: true
  become_user: root
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/wallpaper.jpg'"
    state: present

- name: Copy lockscreenfile
  copy: src=files/lockscreen.jpg dest=/usr/share/backgrounds/lockscreen.jpg owner={{ user_uid }} group={{ user_gid }} mode=644

- name: Set lock screen background
  become: true
  become_user: "{{ user_uid }}"
  dconf:
    key: "/org/gnome/desktop/screensaver/picture-uri"
    value: "'file:///usr/share/backgrounds/lockscreen.jpg'"
    state: present
