- name: Install python-psutil package
  apt: name=python-psutil

- name: Install arc theme
  apt: name=arc-theme
  
- name: Set GTK theme
  become_user: "{{ user_uid }}"
  dconf: key="/org/gnome/desktop/interface/gtk-theme" value="'Arc-Dark'"
  
- name: Copy wallpaper file
  copy: src=files/wallpaper.jpg dest=/opt/gnome/wallpaper.jpg owner={{ user_uid }} group={{ user_gid }} mode=600

- name: Set GNOME wallpaper
  dconf: key="/org/gnome/desktop/background/picture-uri" value="'file:///opt/gnome/wallpaper.jpg'"

- name: Copy lockscreenfile
  copy: src=files/lockscreen.jpg dest="/opt/gnome/lockscreen.jpg" owner={{ user_uid }} group={{ user_gid }} mode=600

- name: Set lock screen background
  become_user: "{{ user_uid }}"
  dconf: key="/org/gnome/desktop/screensaver/picture-uri" value="'file:///opt/gnome/lockscreen.jpg'"
