- name: create ansible user
  user: name=ansible uid=900
  
- name: copy sudoers_ansible
  copy: src=files/sudoers_ansible dest=/etc/sudoers.d/ansible owner=root group=root mode=0440
  
- name: Setting user config in /etc/ansible_user_config.json
  template:
    src: /files/user_config.j2
    dest: /etc/ansible_user_config.json
    user: name=ansible uid=900
    mode: '0644'
